version: "3.9"
services:
  # Backend service
  backend:
    image: aravindwotsabot/backend:${BACKEND_TAG}
    ports:
      - "5002:5002" # Expose the backend port
    env_file:
      - .env # Load environment variables from the .env file
    depends_on:
      - mongodb

  # Frontend service
  frontend:
    build:
      context: ./web  # Specify the directory where your frontend Dockerfile is
      dockerfile: Dockerfile  # Use the Dockerfile located in the 'web' directory
      args:
        VITE_API_BASE_URL: "http://65.2.37.201:5002"  # Pass the API URL
    ports:
      - "80:80" # Map frontend (NGINX) to port 80 for production

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
