name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - develop-v1.0  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Update to your Node.js version

      - name: Install dependencies
        run: |
          set -e
          npm ci  # Use npm ci for faster installs if you have package-lock.json

      - name: Build application
        run: npm run build

      - name: Zip artifact
        run: |
          zip -r application.zip . -x '*.git*' -x 'node_modules/*' -x 'web/node_modules/*' -x 'application.zip'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          version_label: v-${{ github.sha }}
          deployment_package: application.zip
