name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop-v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: aravindwotsabot/backend:${{ github.sha }}
        build-args: |
          FRONTEND_URL=http://65.2.37.201

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with: 
        context: ./web
        push: true
        tags: aravindwotsabot/web:${{ github.sha }}
        build-args: |
          VITE_API_BASE_URL=http://65.2.37.201:5002


    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 65.2.37.201
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Manually set BACKEND_TAG and FRONTEND_TAG to the current commit SHA
          export BACKEND_TAG=${{ github.sha }}
          export FRONTEND_TAG=${{ github.sha }}
          
          # Debugging: Print the environment variables
          echo "BACKEND_TAG is set to: $BACKEND_TAG"
          echo "FRONTEND_TAG is set to: $FRONTEND_TAG"
          
          # Navigate to project directory
          cd /home/ubuntu/crm/
          
          # Pull the latest images using the tags
          docker-compose pull
          
          # Start the services
          docker-compose up -d
          
