name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop-v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: aravindwotsabot/backend:${{ github.sha }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with: 
        context: ./web
        push: true
        tags: aravindwotsabot/web:${{ github.sha }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 65.2.37.201
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        # Pass the GITHUB_SHA as BACKEND_TAG and FRONTEND_TAG
        envs: |
          BACKEND_TAG: '${{ github.sha }}'
          FRONTEND_TAG: '${{ github.sha }}'
        script: |
          cd /home/ubuntu/crm/
          # Debugging: Print the environment variables
          echo "BACKEND_TAG is set to: $BACKEND_TAG"
          echo "FRONTEND_TAG is set to: $FRONTEND_TAG"
          # Pull the latest images
          docker-compose pull
          # Start the services
          docker-compose up -d
