name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop-v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build backend Docker image
      run: docker build -t aravindwotsabot/backend ./backend

    - name: Build frontend Docker image
      run: docker build -t aravindwotsabot/web ./web

    - name: Push backend image
      run: docker push aravindwotsabot/backend

    - name: Push frontend image
      run: docker push aravindwotsabot/web

    - name: Deploy to EC2 via SSH
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@13.233.67.178 << 'EOF'
        docker pull aravindwotsabot/backend
        docker pull aravindwotsabot/web
        docker-compose -f /path/to/docker-compose.yml up -d
        EOF
