name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop-v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: aravindwotsabot/backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./web
        push: true
        tags: aravindwotsabot/web:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 15.206.195.78
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true
        script: |
          docker pull aravindwotsabot/backend:${{ github.sha }}
          docker pull aravindwotsabot/web:${{ github.sha }}
          docker-compose -f /home/ubuntu/crm/docker-compose.yml up -d

